<?php

namespace AppBundle\Repository;

/**
 * PronosticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronosticoRepository extends \Doctrine\ORM\EntityRepository
{
}
